name: Update Data and Deploy

on:
  push:
    branches:
      - master
  schedule:
    - cron: "15 0,8,16 * * *"

jobs:
  syncData:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to set Node version
        uses: actions/checkout@v2
      - name: Uses Node.js 10.x
        # Rollback to Node 10.x to fix "Cannot find module '@babel/compat-data/corejs3-shipped-proposals'" error.
        # The current gatsby version relies on @babel/preset-env v 7.8.7, which has to run under node.js v13.13/12.17.
        # To avoid this conflict, the node version has to be downgraded.
        # ref: https://github.com/nodejs/node/issues/32852
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Checkout to website
        uses: actions/checkout@v2
        with:
          path: master
      - name: Show files
        working-directory: ${{ github.workspace }}
        run: ls -la
      - name: Checkout data repo
        uses: actions/checkout@v2
        with:
          repository: maxMaxineChen/COVID-19-worldwide-json-data-script
          path: sourceData
      - name: Copy the data file
        working-directory: ${{ github.workspace }}
        run: |
          mkdir -p master/data
          cp sourceData/data/data.json master/data/data.json
      - name: Install
        run: |
          cd master 
          npm install
          npm run deploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.COVID19 }}
          publish_dir: ./master/public
